model_params:
  name: 'VanillaVAE'
  in_channels: 4
  latent_dim: 50


data_params:
  data_path: "./Data"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4 ########


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  # gpus: [1]   ############
  gpus: 1
  max_epochs: 200

logging_params:
  save_dir: "vaelogs/"
  name: "VanillaVAE"
  
